program: code/algorithm/main.py
method: grid
project: "non-negative-matrix-factorisation"
name: "noise-salt-and-pepper"
description: "Grid search over multiple models with salt-and-peppered inputs."
parameters:
  seed:
    values: [0, 1, 2, 3, 4]
  model:
    values: ["standard", "l21", "l1_robust"]
  noise_p:
    values: [0.1, 0.2, 0.4]
  noise_r:
    values: [0, 0.5, 1]
  dataset:
    values: ["orl", "yaleb"]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--wandb"
  - "--noise"
  - "salt_and_pepper"
  - ${args}
